name: adhanminima
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.11+14

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  adhan: ^2.0.0-nullsafety.2
  android_intent: ^2.0.2
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^17.2.1+2
  flutter_native_timezone_updated_gradle: ^2.0.3
  flutter_phoenix: ^1.0.0
  flutter_svg: ^2.0.10+1
  geocoding: ^2.0.4
  geolocator: ^11.1.0
  get: ^4.7.2
  http: ^1.2.2
  intl: ^0.17.0
  lottie: ^1.3.0
  rename: ^2.0.1
  restart_app: ^1.1.0
  rxdart: ^0.27.3
  shared_preferences: ^2.5.3
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/bg.jpg
    - assets/location-animation.json

  fonts:
    - family: Halenoir
      fonts:
        - asset: assets/font/Halenoir-Bold.otf
        - asset: assets/font/Halenoir-ThinObl.otf
        - asset: assets/font/Halenoir-UltraLight.otf
        - asset: assets/font/HalenoirText-Regular.otf
          style: italic
