name: adhanminima
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  adhan: ^2.0.0-nullsafety.2
  android_intent: ^2.0.2
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.4.0
  flutter_native_timezone: ^2.0.0
  flutter_phoenix: ^1.0.0
  geocoding: ^2.0.5
  geolocator: ^8.2.0
  get: ^4.6.5
  intl: ^0.17.0
  lottie: ^1.3.0
  rename: ^2.0.1
  restart_app: ^1.1.0
  rxdart: ^0.27.3
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/bg.jpg
    - assets/location-animation.json

  fonts:
    - family: Halenoir
      fonts:
        - asset: assets/font/Halenoir-Bold.otf
        - asset: assets/font/Halenoir-ThinObl.otf
        - asset: assets/font/Halenoir-UltraLight.otf
        - asset: assets/font/HalenoirText-Regular.otf
          style: italic
